// Datos simulados para 20 usuarios
export const usersData = [
  { id: 1, imageLink: 'https://picsum.photos/50/50?random=1', fullName: 'Ana García Pérez', position: 'Directora de Proyecto Senior' },
  { id: 2, imageLink: 'https://picsum.photos/50/50?random=2', fullName: 'Luis Miguel Soto', position: 'Desarrollador Full Stack' },
  { id: 3, imageLink: 'https://picsum.photos/50/50?random=3', fullName: 'Marta Elena Rojas', position: 'Analista de Datos Jr.' },
  { id: 4, imageLink: 'https://picsum.photos/50/50?random=4', fullName: 'Javier Andrés Ríos', position: 'Especialista en Marketing Digital' },
  { id: 5, imageLink: 'https://picsum.photos/50/50?random=5', fullName: 'Sofía Isabel Torres', position: 'Diseñadora UX/UI' },
  { id: 6, imageLink: 'https://picsum.photos/50/50?random=6', fullName: 'Carlos Alberto Mena', position: 'Gerente de Ventas' },
  { id: 7, imageLink: 'https://picsum.photos/50/50?random=7', fullName: 'Valentina Cruz López', position: 'Contadora Pública' },
  { id: 8, imageLink: 'https://picsum.photos/50/50?random=8', fullName: 'Ricardo José Peña', position: 'Ingeniero de Sistemas' },
  { id: 9, imageLink: 'https://picsum.photos/50/50?random=9', fullName: 'Elena María Flores', position: 'Jefa de Recursos Humanos' },
  { id: 10, imageLink: 'https://picsum.photos/50/50?random=10', fullName: 'Diego Fernando Ruiz', position: 'Técnico de Soporte IT' },
  { id: 11, imageLink: 'https://picsum.photos/50/50?random=11', fullName: 'Patricia Andrea Salas', position: 'Editora de Contenido' },
  { id: 12, imageLink: 'https://picsum.photos/50/50?random=12', fullName: 'Héctor Daniel Gómez', position: 'Consultor de Negocios' },
  { id: 13, imageLink: 'https://picsum.photos/50/50?random=13', fullName: 'Adriana Lucía Castro', position: 'Asistente Administrativa' },
  { id: 14, imageLink: 'https://picsum.photos/50/50?random=14', fullName: 'Guillermo Paz Núñez', position: 'Arquitecto Cloud' },
  { id: 15, imageLink: 'https://picsum.photos/50/50?random=15', fullName: 'Laura Cristina Vega', position: 'Científica de Datos' },
  { id: 16, imageLink: 'https://picsum.photos/50/50?random=16', fullName: 'Felipe Eduardo Mota', position: 'Estratega SEO/SEM' },
  { id: 17, imageLink: 'https://picsum.photos/50/50?random=17', fullName: 'Camila Soledad Ramos', position: 'Líder de Equipo' },
  { id: 18, imageLink: 'https://picsum.photos/50/50?random=18', fullName: 'Roberto Jesús Vives', position: 'Abogado Corporativo' },
  { id: 19, imageLink: 'https://picsum.photos/50/50?random=19', fullName: 'Paula Andrea Gil', position: 'Especialista en Capacitación' },
  { id: 20, imageLink: 'https://picsum.photos/50/50?random=20', fullName: 'Andrés Camilo Ferrer', position: 'Subgerente de Operaciones' },
];